var pusheenImages =
{
    "sSnow": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sSnow.png",
    "mSnow": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/mSnow.png",
    "lSnow": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/lSnow.png",
    "sRain": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sRain.png",
    "mRain": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/mRain.png",
    "lRain": "https://res.cloudinary.com/jessawright/image/upload/v1462063482/Pusheen/lRain.png",
    "mWind": "https://res.cloudinary.com/jessawright/image/upload/v1462063480/Pusheen/mWind.png",
    "sWind": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sWind.png",
    "sLightCloudsday": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sLightCloudsDay.png",
    "mLightCloudsday": "https://res.cloudinary.com/jessawright/image/upload/v1462063482/Pusheen/mLightCloudsDay.png",
    "sLightCloudsnight": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sLightCloudsNight.png",
    "mLightCloudsnight": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/mLightCloudsNight.png",
    "sDarkCloudsday": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sDarkCloudsDay.png",
    "mDarkCloudsday": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/mDarkCloudsDay.png",
    "sDarkCloudsnight": "https://res.cloudinary.com/jessawright/image/upload/v1462063482/Pusheen/sDarkCloudsNight.png",
    "mDarkCloudsnight": "https://res.cloudinary.com/jessawright/image/upload/v1462063482/Pusheen/mDarkCloudsNight.png",
    "lightning": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/lightning.png",
    "clearday": "https://res.cloudinary.com/jessawright/image/upload/v1463190458/Pusheen/clearDay.png",
    "clearnight": "https://res.cloudinary.com/jessawright/image/upload/v1462063480/Pusheen/clearNight.png",
    "desaturatedday": "#ACD7E3",
    "saturatedday": "#73DAF9",
    "desaturatednight": "#35353C",
    "saturatednight": "#161657",
    "puddle": "https://res.cloudinary.com/jessawright/image/upload/v1464312534/Pusheen/puddle2.png",
    "snow": "https://res.cloudinary.com/jessawright/image/upload/v1464312773/Pusheen/snow3.png",
    "grass": "https://res.cloudinary.com/jessawright/image/upload/v1464312534/Pusheen/grass2.png",
    "kite": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/kite.png",
    "umbrella": "https://res.cloudinary.com/jessawright/image/upload/v1463190458/Pusheen/umbrella.png",
    "sunglasses": "https://res.cloudinary.com/jessawright/image/upload/v1462063483/Pusheen/sunglasses.png",
    "coat": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/raincoat.png",
    "scarf": "https://res.cloudinary.com/jessawright/image/upload/v1462063482/Pusheen/scarf.png",
    "hat": "https://res.cloudinary.com/jessawright/image/upload/v1462063481/Pusheen/hat.png",
    "boots": "https://res.cloudinary.com/jessawright/image/upload/v1462063480/Pusheen/boots.png"
}
